version: '3.3'
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'stack_db'
      # 
      MYSQL_USER: 'stack_db_user'
      # MSQL_PASSWORD should be passed as environment Variable
      MYSQL_PASSWORD: 
      # Password for root access should be passed as environment Variable
      MYSQL_ROOT_PASSWORD: 
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '23306:3306'
    expose:
      # Opens port 3306 on the container
      - '23306'
      # Where our data will be persisted
    volumes:
      - my-db:/var/lib/mysql

  app:
    build: ./src
    restart: always
    environment:
      RDS_DB_NAME=postgres
      RDS_HOST=db
      RDS_PORT=5432
      RDS_USERNAME=postgres
      RDS_PASSWORD=
    ports:
        - '8000:8000'
    volumes:
        - './src/:/app/'
    command: bash -c "python manage.py migrate --no-input && python manage.py runserver 0.0.0.0:8000"

# Names our volume
volumes:
  my-db:
