version: '3.5'

services:

  nginx-proxy:
    build: .
    logging:
      driver: gelf
      options:
        gelf-address: "udp://localhost:12201"
        tag: "containers"

  app:
    build: .
    logging:
      driver: gelf
      options:
        gelf-address: "udp://localhost:12201"
        tag: "containers"
  db:
    build: .
    logging:
      driver: gelf
      options:
        gelf-address: "udp://localhost:12201"
        tag: "containers"

