version: '3.5'

services:

  proxy:
    build: ./proxy
    logging:
      driver: gelf
      options:
        gelf-address: "udp://127.0.0.1:12201"
        tag: "containers"

  app:
    build: ./app
    logging:
      driver: gelf
      options:
        gelf-address: "udp://127.0.0.1:12201"
        tag: "containers"
  db:
    image: percona/percona-server:5.7
    logging:
      driver: gelf
      options:
        gelf-address: "udp://127.0.0.1:12201"
        tag: "containers"
    depends_on:
      - graylog


  # Elasticsearch: https://www.elastic.co/guide/en/elasticsearch/reference/5.6/docker.html
  elasticsearch:
    networks:
      - sb_internal
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.6.1
    volumes:
      - data_elastics:/usr/share/elasticsearch/data
    environment:
      - http.host=0.0.0.0
      - transport.host=localhost
      - network.host=0.0.0.0
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    #mem_limit: 1g

  # Graylog: https://hub.docker.com/r/graylog/graylog/
  graylog:
    networks:
      - sb_internal
    image: graylog/graylog:3.0
    volumes:
      - data_log:/usr/share/graylog/data/journal
      - ./graylog/config:/usr/share/graylog/data/config
    environment:
      # CHANGE ME (must be at least 16 characters)!
      - GRAYLOG_ROOT_USERNAME=${SB_GRAYLOG_ROOT_USERNAME:-admin}
      - GRAYLOG_PASSWORD_SECRET=${SB_GRAYLOG_PASSWORD_SECRET:-somepasswordpepper}
      # Password: admin
      - GRAYLOG_ROOT_PASSWORD_SHA2=${SB_GRAYLOG_ROOT_PASSWORD_SHA2:-8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918}
      - GRAYLOG_HTTP_EXTERNAL_URI=http://127.0.0.1:9000/
      - GRAYLOG_ROOT_TIMEZONE = America/Mexico_City
    links:
      - mongodb:mongo
      - elasticsearch
    depends_on:
      - mongodb
      - elasticsearch
    ports:
      # Graylog web interface and REST API
      - 127.0.0.1:9000:9000
      # Syslog TCP
      - 127.0.0.1:1514:1514
      # Syslog UDP
      - 127.0.0.1:1514:1514/udp
      # GELF TCP
      - 127.0.0.1:12201:12201
      # GELF UDP
      - 127.0.0.1:12201:12201/udp

  mongodb:
    networks:
      - sb_internal
    image: mongo:3
    volumes:
      - data_mongo:/data/db
