version: '3.5'

services:

  nginx-proxy:
    build: ./nginx
    logging:
      driver: gelf
      options:
        gelf-address: "udp://localhost:12201"
        tag: "containers"

  app:
    build: ./app
    logging:
      driver: gelf
      options:
        gelf-address: "udp://localhost:12201"
        tag: "containers"
  db:
    image: percona/percona-server:5.7
    logging:
      driver: gelf
      options:
        gelf-address: "udp://localhost:12201"
        tag: "containers"

