version: '3.5'
volumes:
  data-portainer:
services:
  portainer:
    #container_name: portainer
    image: portainer/portainer
    command: -H unix:///var/run/docker.sock
    ports:
      - "127.0.0.1:29000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - data-portainer:/data
    labels:
      - "traefik.enable=false"


