version: '3.5'
services:
  app:
    volumes:
      # Mounts the project folder to '/workspace'. The target path inside the container
      # should match what your application expects. In this case, the compose file is
      # in a sub-folder, so we will mount '..'. We'll then reference this as the
      # workspaceFolder in '.devcontainer/devcontainer.json' so VS Code starts here.
      - ./app:/workspace

      # This lets you avoid setting up Git again in the container
      - ~/.gitconfig:/root/.gitconfig

    # Overrides default command so things don't shut down after the process ends.
    command: python3 -m http.server 81
    environment:
      SB_ENV: "VSCODE_COMPOSE"