debug = false
logLevel = "ERROR"
defaultEntryPoints = ["https","http"]
[entryPoints]
  [entryPoints.http]
      address = ":80"
      # [entryPoints.http.redirect]
      #   entryPoint = "https"
  [entryPoints.https]
      address = ":443"
      [entryPoints.https.tls]
[retry]
[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "localhost"
watch = true
exposedByDefault = false
# [acme]
#    caServer = "https://acme-staging-v02.api.letsencrypt.org/directory"
#   email = ""
#   storage = "acme/certs.json"
#   entryPoint = "https"
#   onHostRule = true
#   [acme.httpChallenge]
#      entryPoint = "http"
